### ISSUE TITLE
Ball Is Blocked By Spinner

### ISSUE THREAD

**Issue by hlappano** [freezy/pinball-construction-kit#3]
With the 4.20 upgrade (thanks BTW) I noticed the ball can not move past the spinner.

Easiest way to reproduce it is to set the plunger to spawn a 'Direct Control Pinball' to ease the navigation. From there move the ball to the spin wheel and notice it blocks.

When troubleshooting it a bit. I noticed in the BP_Spinner the 'Cube1' component has a lot of mass to it. By lowering the mass below the mass of the ball, then the force of the ball can move past.  I'm not sure if this is the true fix, or if there is a deeper problem. The reason I say this is because with the older version (4.10), the mass of the cube was the same with the upgrade. So, I figure I just post this with a potential solution since I don't know what really changed.

**Comment by ryugibo** [comment]
I tested older engine version branches.

BP_Spinner blocking started in unreal engine 4.15

Maybe below changes effected that status. Not sure...

[Unreal Engine 4.15 Release notes: ](https://docs.unrealengine.com/en-us/Support/Builds/ReleaseNotes/4_15)
> # Physics
> 
> - Many deprecated collision functions have now been removed from KismetSystemLibrary, and the _NEW postfix has been removed.
> 
> - Cooked PhysX convex element data is now in "body space" instead of “element space”. If you are directly accessing PhysX convex mesh data, you may need to take that into account.
> 
> - Any simulated body with attached kinematic bodies that have different physical materials, or mass overrides, will now have a correct mass distribution.
> 
>   - The old behavior was to use the physical material of the simulated body. This may lead to re-tuning some content. The most likely case is any vehicle with attached kinematics that had special mass properties or mass overrides. As a result of this change, collision boxes with zero mass attached to vehicles will behave correctly.

Cube1's MassInKg set to 0.01, spin works similar before versions.

**Comment by freezy** [comment]
Fixed by #4.
